# -----------------------------------------------------------------
# ARQUIVO DE CONFIGURAÇÃO CENTRAL PARA O PROJETO SolarPV_Analytics
# -----------------------------------------------------------------

# Parâmetros geográficos da simulação
location:
  latitude: -15.7921
  longitude: -47.9114
  altitude: 1100
  tz: 'America/Sao_Paulo'
  name: 'Brasilia-DF'

# Configuração das fontes de dados
data_sources:
  # Caminho para o arquivo TMY (Typical Meteorological Year) do PVGIS
  pvgis_tmy_path: 'data/pvgis/brasilia_pvgis.csv'
  
  # Parâmetros para a API Open-Meteo (usada para previsões, não para simulação TMY)
  open_meteo_api:
    url: "https://api.open-meteo.com/v1/forecast"

# Parâmetros do sistema fotovoltaico para o pvlib.ModelChain
pv_system:
  surface_tilt: 20
  surface_azimuth: 180  # 180 = Virado para o Norte geográfico
  modules_per_string: 10
  strings_per_inverter: 1
  
  # Nomes exatos das bibliotecas SAM (Sandia e CEC)
  # Módulo: Canadian Solar CS6K-275M (Exemplo)
  module_name: 'Canadian_Solar_CS6K_275M'
  # Inversor: SMA Sunny Boy 5000TL-US (Exemplo)
  inverter_name: 'SMA_America__SB5000TL_US_22__240V_'
  
  # Modelo de temperatura e tipo de montagem
  temperature_model_type: 'sapm'
  rack_type: 'open_rack_glass_glass'

# Parâmetros para o período da simulação (usado principalmente para clear-sky)
simulation_times:
  clearsky_start: "2025-07-01"
  clearsky_end: "2025-07-07"
  frequency: "15min"